import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "next-auth";
import AuthProvider from "@/providers/nextAuthProvider/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
    <body className={``}>
      <AuthProvider session={session}>
        {children}
        <Toaster position="top-right" />
      </AuthProvider>
    </body>
  </html>
  );
}
